### ISSUE TITLE
Freezes on "Loading IOS58 Kernel..."

### ISSUE THREAD

**Issue by blueOkiris** [project-slippi/Nintendont#35]
I'm in a Wii U with a hacked virtual Wii with IOS58 version 25.32, and regular Nintendon't works on it just fine.

Slippi's Nintendon't, on the other hand, fails to start and just prints out the message "Loading IOS58 Kernel.." and freezes, requiring pulling the power cable.

I searched for similar issues online, but the only thing I found was not putting meta.xml in the right place and not having IOS58 installed, which doesn't seem to apply here.

I'd really like to get this working, and I feel like it *should* work, so any help would be appreciated

**Comment by NikhilNarayana** [comment]
Slippi Nintendont doesn't come with support for vWii and we have no intention of undoing that change.
