### ISSUE TITLE
Sync with upstream Nintendont

### ISSUE THREAD

**Issue by JerwuQu** [project-slippi/Nintendont#37]
Some people at our locals play with funky HID controllers that we noticed work in upstream Nintendont but not in Slippi Nintendont.

It is likely due to commits like this that are present upstream but not here:
![image](https://github.com/project-slippi/Nintendont/assets/3710677/30bcb210-cb91-4ac4-8dac-54a28de71b58)
![image](https://github.com/project-slippi/Nintendont/assets/3710677/a22a593e-8e12-435c-9c34-b33c9d4e1ce1)

Doing a merge commit looks like it won't conflict in too many files:
![image](https://github.com/project-slippi/Nintendont/assets/3710677/65d57c3d-cf35-4ac4-a478-7829d34b9c0c)

Thanks 🐸

**Comment by NikhilNarayana** [comment]
HID controllers are not supported by our Nintendont because we force Native Control on at all times so there is no benefit for us to sync
